# Site settings
title: Road to Nowhere
header-img: img/home-bg.jpg
email: phellsten@student.unimelb.edu.au
copyright_name: Road to Nowhere
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "phellsten.github.io"
twitter_username: SBootstrap
github_username:  phellsten
facebook_username:  StartBootstrap
email_username:  phellsten@student.unimelb.edu.au

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
